apiVersion: v1
kind: Service
metadata:
  name: customer-service-postgres
  labels:
    app: customer-service
spec:
  ports:
    - port: 5432
  selector:
    app: customer-service
    tier: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-postgres-deployment
  labels:
    app: customer-service
spec:
  selector:
    matchLabels:
      app: customer-service
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: customer-service
        tier: postgres
    spec:
      containers:
        - image: postgres
          name: postgres
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-customer-service-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-customer-service-secrets
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-customer-service-secrets
                key: POSTGRES_DB
          ports:
            - containerPort: 5432
              name: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-server-deployment
  labels:
    app: customer-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service-server
  template:
    metadata:
      labels:
        app: customer-service-server
    spec:
      containers:
        - name: customer-service-server
          image: seppealaerts/customer-service
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8053
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-customer-service-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-customer-service-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB_HOST
              value: "customer-service-postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service-server
  labels:
    app: customer-service-server
spec:
  selector:
    app: customer-service-server
  ports:
    - name: http
      port: 8053
      targetPort: 8053
