apiVersion: v1
kind: Service
metadata:
  name: repairs-service-mongo
  labels:
    app: repairs-service
spec:
  ports:
    - port: 27017
  selector:
    app: repairs-service
    tier: mongo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repairs-service-mongo-deployment
  labels:
    app: repairs-service
spec:
  selector:
    matchLabels:
      app: repairs-service
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: repairs-service
        tier: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - containerPort: 27017
              name: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repairs-service-server-deployment
  labels:
    app: repairs-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repairs-service-server
  template:
    metadata:
      labels:
        app: repairs-service-server
    spec:
      containers:
        - name: repairs-service-server
          image: dbierens/repairs-service
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8052
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:
            - name: MONGODB_HOST
              value: "repairs-service-mongo"
            - name: MONGODB_PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: repairs-service-server
  labels:
    app: repairs-service-server
spec:
  selector:
    app: repairs-service-server
  ports:
    - name: http
      port: 8052
      targetPort: 8052
