apiVersion: v1
kind: Service
metadata:
  name: employee-service-postgres
  labels:
    app: employee-service
spec:
  ports:
    - port: 5432
  selector:
    app: employee-service
    tier: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service-postgres-deployment
  labels:
    app: employee-service
spec:
  selector:
    matchLabels:
      app: employee-service
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: employee-service
        tier: postgres
    spec:
      containers:
        - image: postgres
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-employee-service-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-employee-service-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-employee-service-secrets
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
              name: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service-server-deployment
  labels:
    app: employee-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-service-server
  template:
    metadata:
      labels:
        app: employee-service-server
    spec:
      containers:
        - name: employee-service-server
          image: woutrenkin/employee-service
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8051
          resources:
            limits:
              cpu: 0.2
              memory: "200Mi"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-employee-service-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-employee-service-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB_HOST
              value: "employee-service-postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service-server
  labels:
    app: employee-service-server
spec:
  selector:
    app: employee-service-server
  ports:
    - name: http
      port: 8051
      targetPort: 8051
